# docker-compose.yml
# Version of the Docker Compose file format
version: '3.8'

# Define the services (containers) for your application
services:
  rag_service:
    # Build the Docker image for this service using the Dockerfile in the ./rag_app directory
    build: ./rag_app
    # Define volume mounts to share directories between your host machine and the container
    volumes:
      # Mount the local 'docs' folder to '/app/docs' inside the container.
      # 'ro' makes it read-only, preventing the container from modifying your source documents.
      - ./docs:/app/docs:ro
      # Mount the local 'data/chroma_db' folder to '/app/chroma_db' inside the container.
      # This directory is used by ChromaDB to store the persistent index.
      - ./data/chroma_db:/app/chroma_db
    # Pass environment variables into the container.
    # Docker Compose automatically loads variables from your host environment or the .env file.
    environment:
      # Pass the Google API key needed by the google-generativeai library.
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # You can add other environment variables here if your application requires them.
    # If your application had a web interface, you would map container ports to host ports here:
    # ports:
    #   - "host_port:container_port" # Example: "8000:80"