# prometheus/prometheus.yml
global:
  scrape_interval: 15s # How often to scrape targets
  # evaluation_interval: 15s # Evaluate rules every 15 seconds (for alerts)

scrape_configs:
  - job_name: 'rag_api_service'
    # Scrape metrics from the rag_api_service container
    # Use the service name 'rag_api_service' which resolves internally
    # Metrics are exposed on port 8000 (the FastAPI port) at the /metrics path
    static_configs:
      - targets: ['rag_api_service:8000']
    metrics_path: /metrics # Specify the path where metrics are exposed

  # Optional: Scrape metrics from Elasticsearch itself (if enabled)
  # - job_name: 'elasticsearch'
  #   static_configs:
  #     - targets: ['elasticsearch:9200'] # Use the service name 'elasticsearch'
  #   metrics_path: /_cluster/stats # Or other relevant ES metrics endpoints
  #   scheme: http # Ensure scheme is http