# prometheus/prometheus.yml
# Prometheus configuration file for scraping metrics from the RAG API service
# and optionally from Elasticsearch.
# This file is used by the Prometheus container to configure which services to scrape for metrics.
# Ensure this file is mounted correctly in your docker-compose.yml under the prometheus service.
global:
  scrape_interval: 15s # How often to scrape targets



# This section defines how Prometheus will scrape metrics from the services in the RAG stack.
scrape_configs:
  - job_name: 'rag_api_service'
    # Scrape metrics from the rag_api_service container
    # Use the service name 'rag_api_service' which resolves internally
    # Metrics are exposed on port 8000 (the FastAPI port) at the /metrics path
    static_configs:
      - targets: ['rag_api_service:8000']
    metrics_path: /metrics # Specify the path where metrics are exposed

  # Optional: Scrape metrics from Elasticsearch itself (if enabled)
  #- job_name: 'elasticsearch'
   # static_configs:
   # - targets: ['elasticsearch:9200'] # Use the service name 'elasticsearch'
    #metrics_path: /_cluster/stats # Or other relevant ES metrics endpoints
  #   scheme: http # Ensure scheme is http